### ISSUE TITLE
Jenkins Configuration as Code plugin compatibility

### ISSUE THREAD

**Issue by dav1d-b** [jenkinsci/stashnotifier-plugin#430]
### What feature do you want to see added?

Would it be possible to make this plugin compatible with [Jenkins Configuration as Code plugin](https://plugins.jenkins.io/configuration-as-code/)?

**Comment by piotrkochan** [comment]
I believe it is already compatible. `Configuration as Code` -> `View` gives me:

```
jenkins:
  ...
unclassified:
  ...
  notifyBitbucket:
    considerUnstableAsSuccess: false
    credentialsId: "a4fe3a53-2575-4276-b6bb-6e5ec935fbf0"
    disableInprogressNotification: false
    ignoreUnverifiedSsl: false
    includeBuildNumberInKey: false
    prependParentProjectKey: false
    stashRootUrl: "https://bbtest.com"
```
